# Generated by Django 5.1.7 on 2025-03-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hr',
        ),
    ]
