# Generated by Django 5.1.7 on 2025-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_delete_tbl_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(max_length=30)),
                ('hr_email', models.CharField(max_length=30)),
                ('hr_contact', models.CharField(max_length=30)),
                ('hr_password', models.CharField(max_length=30)),
            ],
        ),
    ]
