# Generated by Django 5.1.7 on 2025-03-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0002_tbl_employee_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_content', models.CharField(max_length=100)),
                ('leave_status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_employee')),
            ],
        ),
    ]
