# Generated by Django 5.1.7 on 2025-03-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_leave',
        ),
    ]
