# Generated by Django 5.1.7 on 2025-03-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_initial'),
        ('HR', '0002_tbl_employee_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_reply', models.CharField(max_length=200)),
                ('complaint_status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_employee')),
            ],
        ),
    ]
