# Generated by Django 5.1.7 on 2025-04-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_hr'),
        ('Employee', '0004_tbl_complaint'),
        ('HR', '0006_delete_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_hr'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_employee'),
        ),
    ]
