# Generated by Django 5.1.7 on 2025-03-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.CharField(max_length=30)),
                ('employee_contact', models.CharField(max_length=30)),
                ('employee_address', models.CharField(max_length=50)),
                ('employee_idnumber', models.CharField(max_length=30)),
                ('employee_photo', models.FileField(upload_to='Assets/Employee/Photo/')),
                ('employee_proof', models.FileField(upload_to='Assets/Employee/Proof/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(auto_now_add=True)),
                ('schedule_todate', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('schedule_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField(auto_now_add=True)),
                ('attendence_intime', models.TimeField()),
                ('attendence_outtime', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_employee')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_role'),
        ),
        migrations.CreateModel(
            name='tbl_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.IntegerField()),
                ('salary_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.tbl_employee')),
            ],
        ),
    ]
