# Generated by Django 5.1.7 on 2025-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employee',
            name='employee_password',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
