# Generated by Django 5.1.7 on 2025-04-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_hr'),
        ('HR', '0002_tbl_employee_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_date', models.DateField(null=True)),
                ('recruitment_content', models.CharField(max_length=500)),
                ('recruitment_lastdate', models.DateField(null=True)),
                ('recruitment_status', models.IntegerField(default=0)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_hr')),
            ],
        ),
    ]
