# Generated by Django 5.1.7 on 2025-04-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_hr'),
        ('HR', '0004_alter_tbl_recruitment_recruitment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_reply', models.CharField(max_length=200)),
                ('complaint_status', models.IntegerField(default=0)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_hr')),
            ],
        ),
    ]
