# Generated by Django 5.1.7 on 2025-04-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
