# Generated by Django 5.1.7 on 2025-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
