# Generated by Django 5.1.7 on 2025-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('usre_address', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('user_resume', models.FileField(upload_to='Assets/User/Resume/')),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
    ]
