# Generated by Django 5.1.7 on 2025-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_photo',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_resume',
        ),
    ]
