# Generated by Django 5.1.7 on 2025-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_user_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
