# Generated by Django 5.1.7 on 2025-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Assets/user/photo/'),
        ),
    ]
